### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Aeyth8** [rm-NoobInCoding/UnrealReZen#35]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Users\Jay\Desktop\Desktopped\UE4Tools\UEcastoc\UEcastoc\Stuff\Output' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)

**Comment by 4rtb** [comment]
Try it as an analogue of this tool: https://forums.unrealengine.com/t/how-to-extract-ucas-and-utoc-io-store-container-files-in-unreal-engine-5/1359694/2

**Comment by Aeyth8** [comment]
Im in UE4

**Comment by 4rtb** [comment]
https://github.com/rm-NoobInCoding/UnrealUnZen/issues/36#issuecomment-2002066950 - best method

**Comment by Aeyth8** [comment]
Your program is garbage

**Comment by rm-NoobInCoding** [comment]
The tool has been updated to the new version and due to many changes, the previous issues have probably been solved by now (see readme). If you still have a problem, create a new issue
