### ISSUE TITLE
Trying to add Langues to TL by adding it to *.ini Repacking breaks

### ISSUE THREAD

**Issue by Dastano** [rm-NoobInCoding/UnrealReZen#45]
**Describe the bug** 
When trying to create a Patch File for TL to add Korean Text Language the Repacking fails.

Command used:

UnrealReZen.exe -g "D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks" -c "C:\Users\XX\Downloads\MR\Output\Exports" -o "D:\SteamLibrary\steamapps\common\Throne and Liberty\pakchunk0-WindowsNoEditor_4_P.utoc" -e "GAME_UE4_LATEST" -a 0x005F3903E2E5C5A1B85442C196F2D18321D7203F38E4E19812FEFE17AD26440C 

**Tool outputs**
[12:47:37 INF] Mounting DefaultTLLanguagesSettings.ini
Unhandled exception. Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'CUE4Parse.UE4.Pak.Objects.FPakEntry' does not contain a definition for 'ChunkId'
   at CallSite.Target(Closure, CallSite, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at UnrealReZen.Program.RunOptionsAndReturnExitCode(Options opts) in C:\Users\PCMOD\source\repos\UnrealReZen\UnrealReZen\Program.cs:line 137
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at UnrealReZen.Program.Main(String[] args) in C:\Users\PCMOD\source\repos\UnrealReZen\UnrealReZen\Program.cs:line 59
   
   Also some Weird errors:
   
   [12:47:36 INF] Loading Game Archives...
[12:47:37 WRN] CUE4Parse.UE4.IO.Objects.FIoStatusException: Failed to open container partition 0 for D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk101-WindowsNoEditor_0_P.utoc (FileOpenFailed)
 ---> System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk101-WindowsNoEditor_0_P.ucas'.
File name: 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk101-WindowsNoEditor_0_P.ucas'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider.<IterateFiles>b__7_0(String it)
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   --- End of inner exception stack trace ---
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   at CUE4Parse.FileProvider.Vfs.AbstractVfsFileProvider.RegisterVfs(FArchive archive, Stream stream, Func`2 openContainerStreamFunc)
[12:47:37 WRN] CUE4Parse.UE4.IO.Objects.FIoStatusException: Failed to open container partition 0 for D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk101-WindowsNoEditor_1_P.utoc (FileOpenFailed)
 ---> System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk101-WindowsNoEditor_1_P.ucas'.
File name: 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk101-WindowsNoEditor_1_P.ucas'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider.<IterateFiles>b__7_0(String it)
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   --- End of inner exception stack trace ---
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   at CUE4Parse.FileProvider.Vfs.AbstractVfsFileProvider.RegisterVfs(FArchive archive, Stream stream, Func`2 openContainerStreamFunc)
[12:47:37 WRN] CUE4Parse.UE4.IO.Objects.FIoStatusException: Failed to open container partition 0 for D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk101-WindowsNoEditor_2_P.utoc (FileOpenFailed)
 ---> System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk101-WindowsNoEditor_2_P.ucas'.
File name: 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk101-WindowsNoEditor_2_P.ucas'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider.<IterateFiles>b__7_0(String it)
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   --- End of inner exception stack trace ---
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   at CUE4Parse.FileProvider.Vfs.AbstractVfsFileProvider.RegisterVfs(FArchive archive, Stream stream, Func`2 openContainerStreamFunc)
[12:47:37 WRN] CUE4Parse.UE4.IO.Objects.FIoStatusException: Failed to open container partition 0 for D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk101-WindowsNoEditor_3_P.utoc (FileOpenFailed)
 ---> System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk101-WindowsNoEditor_3_P.ucas'.
File name: 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk101-WindowsNoEditor_3_P.ucas'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider.<IterateFiles>b__7_0(String it)
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   --- End of inner exception stack trace ---
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   at CUE4Parse.FileProvider.Vfs.AbstractVfsFileProvider.RegisterVfs(FArchive archive, Stream stream, Func`2 openContainerStreamFunc)
[12:47:37 WRN] CUE4Parse.UE4.IO.Objects.FIoStatusException: Failed to open container partition 0 for D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk2-WindowsNoEditor_0_P.utoc (FileOpenFailed)
 ---> System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk2-WindowsNoEditor_0_P.ucas'.
File name: 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk2-WindowsNoEditor_0_P.ucas'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider.<IterateFiles>b__7_0(String it)
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   --- End of inner exception stack trace ---
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   at CUE4Parse.FileProvider.Vfs.AbstractVfsFileProvider.RegisterVfs(FArchive archive, Stream stream, Func`2 openContainerStreamFunc)
[12:47:37 WRN] CUE4Parse.UE4.IO.Objects.FIoStatusException: Failed to open container partition 0 for D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk2-WindowsNoEditor_1_P.utoc (FileOpenFailed)
 ---> System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk2-WindowsNoEditor_1_P.ucas'.
File name: 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk2-WindowsNoEditor_1_P.ucas'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider.<IterateFiles>b__7_0(String it)
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   --- End of inner exception stack trace ---
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   at CUE4Parse.FileProvider.Vfs.AbstractVfsFileProvider.RegisterVfs(FArchive archive, Stream stream, Func`2 openContainerStreamFunc)
[12:47:37 WRN] CUE4Parse.UE4.IO.Objects.FIoStatusException: Failed to open container partition 0 for D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk2-WindowsNoEditor_2_P.utoc (FileOpenFailed)
 ---> System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk2-WindowsNoEditor_2_P.ucas'.
File name: 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk2-WindowsNoEditor_2_P.ucas'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider.<IterateFiles>b__7_0(String it)
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   --- End of inner exception stack trace ---
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   at CUE4Parse.FileProvider.Vfs.AbstractVfsFileProvider.RegisterVfs(FArchive archive, Stream stream, Func`2 openContainerStreamFunc)
[12:47:37 WRN] CUE4Parse.UE4.IO.Objects.FIoStatusException: Failed to open container partition 0 for D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk2-WindowsNoEditor_3_P.utoc (FileOpenFailed)
 ---> System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk2-WindowsNoEditor_3_P.ucas'.
File name: 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk2-WindowsNoEditor_3_P.ucas'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider.<IterateFiles>b__7_0(String it)
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   --- End of inner exception stack trace ---
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   at CUE4Parse.FileProvider.Vfs.AbstractVfsFileProvider.RegisterVfs(FArchive archive, Stream stream, Func`2 openContainerStreamFunc)
[12:47:37 WRN] CUE4Parse.UE4.IO.Objects.FIoStatusException: Failed to open container partition 0 for D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk3-WindowsNoEditor_0_P.utoc (FileOpenFailed)
 ---> System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk3-WindowsNoEditor_0_P.ucas'.
File name: 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk3-WindowsNoEditor_0_P.ucas'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider.<IterateFiles>b__7_0(String it)
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   --- End of inner exception stack trace ---
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   at CUE4Parse.FileProvider.Vfs.AbstractVfsFileProvider.RegisterVfs(FArchive archive, Stream stream, Func`2 openContainerStreamFunc)
[12:47:37 WRN] CUE4Parse.UE4.IO.Objects.FIoStatusException: Failed to open container partition 0 for D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk3-WindowsNoEditor_1_P.utoc (FileOpenFailed)
 ---> System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk3-WindowsNoEditor_1_P.ucas'.
File name: 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk3-WindowsNoEditor_1_P.ucas'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider.<IterateFiles>b__7_0(String it)
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   --- End of inner exception stack trace ---
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   at CUE4Parse.FileProvider.Vfs.AbstractVfsFileProvider.RegisterVfs(FArchive archive, Stream stream, Func`2 openContainerStreamFunc)
[12:47:37 WRN] CUE4Parse.UE4.IO.Objects.FIoStatusException: Failed to open container partition 0 for D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk3-WindowsNoEditor_2_P.utoc (FileOpenFailed)
 ---> System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk3-WindowsNoEditor_2_P.ucas'.
File name: 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk3-WindowsNoEditor_2_P.ucas'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider.<IterateFiles>b__7_0(String it)
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   --- End of inner exception stack trace ---
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   at CUE4Parse.FileProvider.Vfs.AbstractVfsFileProvider.RegisterVfs(FArchive archive, Stream stream, Func`2 openContainerStreamFunc)
[12:47:37 WRN] CUE4Parse.UE4.IO.Objects.FIoStatusException: Failed to open container partition 0 for D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk3-WindowsNoEditor_3_P.utoc (FileOpenFailed)
 ---> System.IO.FileNotFoundException: Could not find file 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk3-WindowsNoEditor_3_P.ucas'.
File name: 'D:\SteamLibrary\steamapps\common\Throne and Liberty\TL\Content\Paks\pakchunk3-WindowsNoEditor_3_P.ucas'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at CUE4Parse.FileProvider.DefaultFileProvider.<IterateFiles>b__7_0(String it)
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   --- End of inner exception stack trace ---
   at CUE4Parse.UE4.IO.IoStoreReader..ctor(FArchive tocStream, Func`2 openContainerStreamFunc, EIoStoreTocReadOptions readOptions)
   at CUE4Parse.FileProvider.Vfs.AbstractVfsFileProvider.RegisterVfs(FArchive archive, Stream stream, Func`2 openContainerStreamFunc)
[12:47:37 WRN] "pakchunk1004-WindowsNoEditor_3_P.utoc" has strange mount point "/", mounting to root
[12:47:37 WRN] "pakchunk101-WindowsNoEditor.utoc" has strange mount point "/", mounting to root
[12:47:37 INF] IoStore "pakchunk1005-WindowsNoEditor.utoc": 275 files, mount point: "TL/Content/Map/ElmoredenWP/Levels/Landscape250/0/", version 3 in 00:00:00.0001740
[12:47:37 INF] IoStore "pakchunk101-WindowsNoEditor.utoc": 0 files, version 3 in 00:00:00.0006619
[12:47:37 INF] IoStore "pakchunk1003-WindowsNoEditor_2_P.utoc": 161 files, mount point: "TL/Content/Map/ElmoredenWP/Levels/Landscape250/0/", version 3 in 00:00:00.0014595
[12:47:37 INF] IoStore "pakchunk1004-WindowsNoEditor_3_P.utoc": 0 files, version 3 in 00:00:00.0014475
[12:47:37 INF] IoStore "pakchunk1001-WindowsNoEditor_2_P.utoc": 161 files, mount point: "TL/Content/Map/ElmoredenWP/Levels/Landscape250/0/", version 3 in 00:00:00.0016726
[12:47:37 INF] IoStore "pakchunk1000-WindowsNoEditor.utoc": 274 files, mount point: "TL/Content/Map/ElmoredenWP/Levels/Landscape250/0/", version 3 in 00:00:00.0016959
[12:47:37 WRN] "pakchunk1000-WindowsNoEditor_2_P.pak" has strange mount point "/", mounting to root
[12:47:37 WRN] "pakchunk2-WindowsNoEditor_2_P.pak" has strange mount point "/", mounting to root
[12:47:37 WRN] "pakchunk1001-WindowsNoEditor_0_P.pak" has strange mount point "/", mounting to root
[12:47:37 WRN] "pakchunk1005-WindowsNoEditor_3_P.pak" has strange mount point "/", mounting to root

**Expected behavior**
Create a Patch

**Game Name**
Throne and Liberty F2P on Steam

**Additional context**
Repacking without AES Key works, but then the File isn't accepted by the Game, repacking using the Key breaks.

**Comment by rm-NoobInCoding** [comment]
Please send a screen shot of game paks folder

**Comment by Dastano** [comment]
![image](https://github.com/user-attachments/assets/113e44b9-9ec3-434e-9f83-58d7a0f263d3)
![image](https://github.com/user-attachments/assets/896b8aef-64fc-457f-b1a7-149926ec35b0)
![image](https://github.com/user-attachments/assets/30b70af2-c5c5-49e4-97fa-1023b11b3896)
![image](https://github.com/user-attachments/assets/9e542a7e-36e2-47c1-bac3-5ead4772168a)

![image](https://github.com/user-attachments/assets/1886cea0-a5e7-4918-bb00-035cf1690983)
![image](https://github.com/user-attachments/assets/91e2fcba-ce72-48dc-8c92-d5fc3a8f3eaa)
![image](https://github.com/user-attachments/assets/3b4e668a-dbdb-451e-a35d-1947b674d9e3)


Sorry lot of files ^.^

**Comment by rm-NoobInCoding** [comment]
Duplicate of #47

**Comment by rm-NoobInCoding** [comment]
Please read Important Notes (4) in readme
