### ISSUE TITLE
unhandled exception when packing mod

### ISSUE THREAD

**Issue by Paytonpay** [rm-NoobInCoding/UnrealReZen#47]
Im getting an unhandled exception error when attempting to pack a mod:

Unhandled exception. Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'CUE4Parse.UE4.Pak.Objects.FPakEntry' does not contain a definition for 'ChunkId'
   at CallSite.Target(Closure, CallSite, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at UnrealReZen.Program.RunOptionsAndReturnExitCode(Options opts) in C:\Users\PCMOD\source\repos\UnrealReZen\UnrealReZen\Program.cs:line 137
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at UnrealReZen.Program.Main(String[] args) in C:\Users\PCMOD\source\repos\UnrealReZen\UnrealReZen\Program.cs:line 59
PS C:\Users\payho\Downloads\UnrealReZen_V01>

input command: 

./UnrealReZen.exe --content-path C:\Users\payho\Downloads\UnrealReZen_V01\paymod --compression-format Zlib --engine-version GAME_UE5_5 --game-dir D:\SteamLibrary\steamapps\common\AbioticFactor\AbioticFactor\Content\Paks  --output-path D:\SteamLibrary\steamapps\common\AbioticFactor\AbioticFactor\Content\Paks\paymod.utoc

Game is Abiotic Factor running on ue5_5
The fmodel export folder path is unchanged from the original

Any ideas on whats going wrong? : (

**Comment by rm-NoobInCoding** [comment]
Your game probably needs custom CUE4Parse lib support
Contact FModel to confirm its support
I will update the library next week to see if it will be fixed or not.
Meanwhile, you can upload one of the original utoc/ucas files for faster help

**Comment by rm-NoobInCoding** [comment]
Please upload the files that you wanna pack

**Comment by Varyag-Ericsson** [comment]
[pakchunk0-Windows.zip](https://github.com/user-attachments/files/17444852/pakchunk0-Windows.zip)
Hi! I have the same issue, but with Lollipop Chainsaw. I've uploaded utoc w/o ucas, cause ucas is 13gb. Can upload if you need it.

**Comment by rm-NoobInCoding** [comment]
> Please upload the files that you wanna pack

^^

**Comment by Varyag-Ericsson** [comment]
[MyPatchedContent.zip](https://github.com/user-attachments/files/17445139/MyPatchedContent.zip)
These?

**Comment by Release** [comment]
Perhaps the error can be circumvented by checking if there is a record for the modified file in the .utoc file at all. Perhaps it is stored in a pak file and does not need to be packaged in .ucas.

I had a similar problem with the Game.locmeta file. I got around it by fixing the line from:
`var filedata = provider.Files.Values.Where(a => a.Path.Equals(filename, StringComparison.CurrentCultureIgnoreCase));`
to:
`var filedata = provider.Files.Values.Where(a => Path.GetExtension(((AbstractVfsReader)((VfsEntry)a).Vfs).Name) == ".utoc" && a.Path.Equals(filename, StringComparison.CurrentCultureIgnoreCase));`

And the necessary file and the other one, which was not there at all, I packed into a regular pak-file using the UnrealPak.exe utility from the UE4 package of the corresponding version, replacing the one created by this utility.

**Comment by SwathingSoap** [comment]
Hi, is it will be fixed?

**Comment by SwathingSoap** [comment]
thanks
